version: '3'

volumes:
  postgres_data: { }
  
services:
  postgres:
    container_name: basys.postgres
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=QAZwsx!@#
    ports:
      - "7432:5432"