version: '3'

services:
  basys:
    container_name: basys.app
    image: basysteam/basys:latest
    restart: always
    ports:
      - 13080:8080
    environment:
      # CurrentApp
      InitAppSettings:CurrentApp:Id: main
      InitAppSettings:CurrentApp:Title: Main

      # Sa. Параметры для создания системной базы данных.
      # Логин супер администратора.
      InitAppSettings:Sa:Login: sa@thebasys.com
      # Пароль супер администратора.
      InitAppSettings:Sa:Password: 111111
      # Вид СУБД: 0 - MS SQL, 1 - PG SQL.
      InitAppSettings:Sa:DbKind: 1
      # Строка подключения к системной базе данных.
      InitAppSettings:Sa:ConnectionString: Server=host.docker.internal;Port=5432;Database=basys_system;User ID=postgres;Password=1;Timeout=60;

      # MainDb. Параметры для создания рабочей базы данных.
      # Имя базы данных (может содержать латинские буквы в нижнем регистре, цифры и символ подчеркивания)
      InitAppSettings:MainDb:Name: basys_work_1
      # Вид СУБД: 0 - MS SQL, 1 - PG SQL
      InitAppSettings:MainDb:DbKind: 1
      # Строка подключения к базе данных.
      InitAppSettings:MainDb:ConnectionString: Server=host.docker.internal;Port=5432;Database=basys_work_1;User ID=postgres;Password=1;Timeout=60;
      # Логин администратора.
      InitAppSettings:MainDb:AdminLogin: admin@thebasys.com
      # Пароль администратора. 
      InitAppSettings:MainDb:AdminPassword: 111111
      # Язык по умолчанию для администратора: ru | en
      InitAppSettings:MainDb:Culture: ru
    extra_hosts:
      - "host.docker.internal:host-gateway"
