version: '3'

services:
  basys:
    container_name: basys.app
    image: basysteam/basys:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      #      CurrentApp
      InitAppSettings:CurrentApp:Id: main
      InitAppSettings:CurrentApp:Title: Main
      #      Sa
      InitAppSettings:Sa:Login: sa@mail.ru
      InitAppSettings:Sa:Password: 111111
      InitAppSettings:Sa:DbKind: 1
      InitAppSettings:Sa:ConnectionString: Server=host.docker.internal;Port=5432;Database=basys_system_test;User ID=postgres;Password=1;Timeout=60;
      #      MainDb
      InitAppSettings:MainDb:Name: db1
      InitAppSettings:MainDb:DbKind: 1
      InitAppSettings:MainDb:ConnectionString: Server=host.docker.internal;Port=5432;Database=basys_test_1;User ID=postgres;Password=1;Timeout=60;
      InitAppSettings:MainDb:AdminLogin: admin@mail.ru
      InitAppSettings:MainDb:AdminPassword: 111111
      InitAppSettings:MainDb:Culture: ru
    extra_hosts:
      - "host.docker.internal:host-gateway"