//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaSys.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DictMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DictMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaSys.Translation.DictMain", typeof(DictMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App constants record created.
        /// </summary>
        public static string AppConstantsRecordCreated {
            get {
                return ResourceManager.GetString("AppConstantsRecordCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App constants record deleted.
        /// </summary>
        public static string AppConstantsRecordDeleted {
            get {
                return ResourceManager.GetString("AppConstantsRecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App constants record updated.
        /// </summary>
        public static string AppConstantsRecordUpdated {
            get {
                return ResourceManager.GetString("AppConstantsRecordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change password.
        /// </summary>
        public static string CannotChangePassword {
            get {
                return ResourceManager.GetString("CannotChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create app constants record.
        /// </summary>
        public static string CannotCreateAppConstantsRecord {
            get {
                return ResourceManager.GetString("CannotCreateAppConstantsRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create user.
        /// </summary>
        public static string CannotCreateUser {
            get {
                return ResourceManager.GetString("CannotCreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete app constants record.
        /// </summary>
        public static string CannotDeleteAppConstantsRecord {
            get {
                return ResourceManager.GetString("CannotDeleteAppConstantsRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete user.
        /// </summary>
        public static string CannotDeleteUser {
            get {
                return ResourceManager.GetString("CannotDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CannotDisableUser.
        /// </summary>
        public static string CannotDisableUser {
            get {
                return ResourceManager.GetString("CannotDisableUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot enable user.
        /// </summary>
        public static string CannotEnableUser {
            get {
                return ResourceManager.GetString("CannotEnableUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find app constants record.
        /// </summary>
        public static string CannotFindAppConstantsRecord {
            get {
                return ResourceManager.GetString("CannotFindAppConstantsRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find user.
        /// </summary>
        public static string CannotFindUser {
            get {
                return ResourceManager.GetString("CannotFindUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get app constants records list.
        /// </summary>
        public static string CannotGetAppConstantsRecordsList {
            get {
                return ResourceManager.GetString("CannotGetAppConstantsRecordsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get users list.
        /// </summary>
        public static string CannotGetUsersList {
            get {
                return ResourceManager.GetString("CannotGetUsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update app constants record.
        /// </summary>
        public static string CannotUpdateAppConstantsRecord {
            get {
                return ResourceManager.GetString("CannotUpdateAppConstantsRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update user.
        /// </summary>
        public static string CannotUpdateUser {
            get {
                return ResourceManager.GetString("CannotUpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty app constants record list.
        /// </summary>
        public static string EmptyAppConstantsRecordList {
            get {
                return ResourceManager.GetString("EmptyAppConstantsRecordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application title should not be empty.
        /// </summary>
        public static string EmptyApplicationTitle {
            get {
                return ResourceManager.GetString("EmptyApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty users list.
        /// </summary>
        public static string EmptyUsersList {
            get {
                return ResourceManager.GetString("EmptyUsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is the only active administrator.
        /// </summary>
        public static string OnlyActiveAdministrator {
            get {
                return ResourceManager.GetString("OnlyActiveAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created.
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted.
        /// </summary>
        public static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User disabled.
        /// </summary>
        public static string UserDisabled {
            get {
                return ResourceManager.GetString("UserDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User enabled.
        /// </summary>
        public static string UserEnabled {
            get {
                return ResourceManager.GetString("UserEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users list refreshed.
        /// </summary>
        public static string UsersListRefreshed {
            get {
                return ResourceManager.GetString("UsersListRefreshed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User updated.
        /// </summary>
        public static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid database uid format.
        /// </summary>
        public static string WrongDataBaseUidFormat {
            get {
                return ResourceManager.GetString("WrongDataBaseUidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password format.
        /// </summary>
        public static string WrongPasswordFormat {
            get {
                return ResourceManager.GetString("WrongPasswordFormat", resourceCulture);
            }
        }
    }
}
