//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaSys.FluentQueries.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaSys.FluentQueries.UnitTests.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [cat_currency]
        ///ADD [code] NVARCHAR(3) NOT NULL;.
        /// </summary>
        internal static string AlterTableAddOneColumnMsSQl {
            get {
                return ResourceManager.GetString("AlterTableAddOneColumnMsSQl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;cat_currency&quot;
        ///ADD COLUMN &quot;code&quot; varchar(3) NOT NULL;.
        /// </summary>
        internal static string AlterTableAddOneColumnPgSQl {
            get {
                return ResourceManager.GetString("AlterTableAddOneColumnPgSQl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [cat_currency]
        ///ADD [code] NVARCHAR(3) NOT NULL,
        ///[title] NVARCHAR(100) NOT NULL;.
        /// </summary>
        internal static string AlterTableAddTwoColumnsMsSQl {
            get {
                return ResourceManager.GetString("AlterTableAddTwoColumnsMsSQl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;cat_currency&quot;
        ///ADD COLUMN &quot;code&quot; varchar(3) NOT NULL,
        ///ADD COLUMN &quot;title&quot; varchar(100) NOT NULL;.
        /// </summary>
        internal static string AlterTableAddTwoColumnsPgSQl {
            get {
                return ResourceManager.GetString("AlterTableAddTwoColumnsPgSQl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [cat_currency]
        ///ALTER COLUMN [rate] NVARCHAR(100) NULL;.
        /// </summary>
        internal static string AlterTableChangeDataTypeOfColumnMsSQl {
            get {
                return ResourceManager.GetString("AlterTableChangeDataTypeOfColumnMsSQl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;cat_currency&quot;
        ///ALTER COLUMN &quot;rate&quot; varchar(100) NULL USING &quot;rate&quot;::varchar(100);.
        /// </summary>
        internal static string AlterTableChangeDataTypeOfColumnPgSQl {
            get {
                return ResourceManager.GetString("AlterTableChangeDataTypeOfColumnPgSQl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [cat_currency]
        ///DROP COLUMN [code];.
        /// </summary>
        internal static string AlterTableDropOneColumnMsSQl {
            get {
                return ResourceManager.GetString("AlterTableDropOneColumnMsSQl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;cat_currency&quot;
        ///DROP COLUMN &quot;code&quot;;.
        /// </summary>
        internal static string AlterTableDropOneColumnPgSQl {
            get {
                return ResourceManager.GetString("AlterTableDropOneColumnPgSQl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE [cat_currency]
        ///DROP COLUMN [code],
        ///DROP COLUMN [title];.
        /// </summary>
        internal static string AlterTableDropTwoColumnsMsSQl {
            get {
                return ResourceManager.GetString("AlterTableDropTwoColumnsMsSQl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;cat_currency&quot;
        ///DROP COLUMN &quot;code&quot;,
        ///DROP COLUMN &quot;title&quot;;.
        /// </summary>
        internal static string AlterTableDropTwoColumnsPgSQl {
            get {
                return ResourceManager.GetString("AlterTableDropTwoColumnsPgSQl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXEC sp_rename &apos;cat_currency.title&apos;, &apos;description&apos;, &apos;COLUMN&apos;;.
        /// </summary>
        internal static string AlterTableRenameColumnMsSQl {
            get {
                return ResourceManager.GetString("AlterTableRenameColumnMsSQl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALTER TABLE &quot;cat_currency&quot;
        ///RENAME COLUMN &quot;title&quot; TO &quot;description&quot;;.
        /// </summary>
        internal static string AlterTableRenameColumnPgSQl {
            get {
                return ResourceManager.GetString("AlterTableRenameColumnPgSQl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE sys_metadata_groups (
        ///uid UNIQUEIDENTIFIER PRIMARY KEY,
        ///parentuid UNIQUEIDENTIFIER NULL,
        ///title NVARCHAR(100) NOT NULL,
        ///iconclass NVARCHAR(20) NULL,
        ///memo NVARCHAR(300) NULL,
        ///isstandard BIT NOT NULL
        ///);.
        /// </summary>
        internal static string CreateTableMetadataGroupMsSql {
            get {
                return ResourceManager.GetString("CreateTableMetadataGroupMsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE sys_metadata_groups (
        ///uid UUID PRIMARY KEY,
        ///parentuid uuid NULL,
        ///title varchar(100) NOT NULL,
        ///iconclass varchar(20) NULL,
        ///memo varchar(300) NULL,
        ///isstandard boolean NOT NULL
        ///);.
        /// </summary>
        internal static string CreateTableMetadataGroupPgSql {
            get {
                return ResourceManager.GetString("CreateTableMetadataGroupPgSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE sys_meta_object_kinds (
        ///uid UNIQUEIDENTIFIER PRIMARY KEY,
        ///title NVARCHAR(100) NOT NULL,
        ///name NVARCHAR(40) NOT NULL UNIQUE,
        ///prefix NVARCHAR(4) NOT NULL UNIQUE,
        ///storedata BIT NOT NULL,
        ///isreference BIT NOT NULL,
        ///isstandard BIT NOT NULL,
        ///version BIGINT NOT NULL,
        ///memo NVARCHAR(300) NULL,
        ///settingsstorage VARBINARY(MAX) NOT NULL
        ///);.
        /// </summary>
        internal static string CreateTableMetaObjectKindMsSql {
            get {
                return ResourceManager.GetString("CreateTableMetaObjectKindMsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE sys_meta_object_kinds (
        ///uid UUID PRIMARY KEY,
        ///title varchar(100) NOT NULL,
        ///name varchar(40) NOT NULL UNIQUE,
        ///prefix varchar(4) NOT NULL UNIQUE,
        ///storedata boolean NOT NULL,
        ///isreference boolean NOT NULL,
        ///isstandard boolean NOT NULL,
        ///version bigint NOT NULL,
        ///memo varchar(300) NULL,
        ///settingsstorage bytea NOT NULL
        ///);.
        /// </summary>
        internal static string CreateTableMetaObjectKindPgSql {
            get {
                return ResourceManager.GetString("CreateTableMetaObjectKindPgSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE sys_metadata_kinds (
        ///uid UNIQUEIDENTIFIER PRIMARY KEY,
        ///title NVARCHAR(100) NOT NULL,
        ///prefix NVARCHAR(4) NOT NULL UNIQUE
        ///);.
        /// </summary>
        internal static string CreateTableWithUniqueColumnMsSql {
            get {
                return ResourceManager.GetString("CreateTableWithUniqueColumnMsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE sys_metadata_kinds (
        ///uid UUID PRIMARY KEY,
        ///title varchar(100) NOT NULL,
        ///prefix varchar(4) NOT NULL UNIQUE
        ///);.
        /// </summary>
        internal static string CreateTableWithUniqueColumnPgSql {
            get {
                return ResourceManager.GetString("CreateTableWithUniqueColumnPgSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONCAT([tableName].[code], &apos; - &apos;, [tableName].[title]) AS text.
        /// </summary>
        internal static string DisplayCodeAndTitleMsSql {
            get {
                return ResourceManager.GetString("DisplayCodeAndTitleMsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONCAT(&quot;tableName&quot;.&quot;code&quot;, &apos; - &apos;, &quot;tableName&quot;.&quot;title&quot;) AS text.
        /// </summary>
        internal static string DisplayCodeAndTitlePgSql {
            get {
                return ResourceManager.GetString("DisplayCodeAndTitlePgSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [metadata_groups]
        ///([uid], [parentuid])
        ///VALUES
        ///(@uid, @parentuid);.
        /// </summary>
        internal static string InsertAutoFillValuesMsSql {
            get {
                return ResourceManager.GetString("InsertAutoFillValuesMsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &quot;metadata_groups&quot;
        ///(&quot;uid&quot;, &quot;parentuid&quot;)
        ///VALUES
        ///(@uid, @parentuid);.
        /// </summary>
        internal static string InsertAutoFillValuesPgSql {
            get {
                return ResourceManager.GetString("InsertAutoFillValuesPgSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [metadata_groups]
        ///([uid], [parentuid])
        ///VALUES
        ///(@uid, @parentuid);.
        /// </summary>
        internal static string InsertOneRowMsSql {
            get {
                return ResourceManager.GetString("InsertOneRowMsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &quot;metadata_groups&quot;
        ///(&quot;uid&quot;, &quot;parentuid&quot;)
        ///VALUES
        ///(@uid, @parentuid);.
        /// </summary>
        internal static string InsertOneRowPgSql {
            get {
                return ResourceManager.GetString("InsertOneRowPgSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [cat_currency]
        ///([name], [code], [title])
        ///OUTPUT INSERTED.id
        ///VALUES
        ///(@name, @code, @title);.
        /// </summary>
        internal static string InsertReturnIdMsSql {
            get {
                return ResourceManager.GetString("InsertReturnIdMsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &quot;cat_currency&quot;
        ///(&quot;name&quot;, &quot;code&quot;, &quot;title&quot;)
        ///VALUES
        ///(@name, @code, @title)
        ///RETURNING id;.
        /// </summary>
        internal static string InsertReturnIdPgSql {
            get {
                return ResourceManager.GetString("InsertReturnIdPgSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 *
        ///FROM [my_table];.
        /// </summary>
        internal static string SelectTopMsSql {
            get {
                return ResourceManager.GetString("SelectTopMsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 *
        ///FROM [my_table]
        ///ORDER BY name desc;.
        /// </summary>
        internal static string SelectTopOrderByMsSql {
            get {
                return ResourceManager.GetString("SelectTopOrderByMsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM &quot;my_table&quot;
        ///ORDER BY name desc
        ///LIMIT 1;.
        /// </summary>
        internal static string SelectTopOrderByPgSql {
            get {
                return ResourceManager.GetString("SelectTopOrderByPgSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM &quot;my_table&quot;
        ///LIMIT 1;.
        /// </summary>
        internal static string SelectTopPgSql {
            get {
                return ResourceManager.GetString("SelectTopPgSql", resourceCulture);
            }
        }
    }
}
