//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaSys.FluentQueries.UnitTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BaSys.FluentQueries.UnitTests.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE sys_metadata_groups (
        ///uid UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
        ///parentuid UNIQUEIDENTIFIER NULL,
        ///title NVARCHAR(100) NOT NULL,
        ///iconclass NVARCHAR(20) NULL,
        ///memo NVARCHAR(300) NULL,
        ///isstandard BIT NOT NULL
        ///);.
        /// </summary>
        internal static string CreateTableMetadataGroupMsSql {
            get {
                return ResourceManager.GetString("CreateTableMetadataGroupMsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE sys_metadata_groups (
        ///uid UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        ///parentuid uuid NULL,
        ///title varchar(100) NOT NULL,
        ///iconclass varchar(20) NULL,
        ///memo varchar(300) NULL,
        ///isstandard boolean NOT NULL
        ///);.
        /// </summary>
        internal static string CreateTableMetadataGroupPgSql {
            get {
                return ResourceManager.GetString("CreateTableMetadataGroupPgSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE sys_metadata_kinds (
        ///uid UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
        ///title NVARCHAR(100) NOT NULL,
        ///prefix NVARCHAR(4) NOT NULL UNIQUE
        ///);.
        /// </summary>
        internal static string CreateTableWithUniqueColumnMsSql {
            get {
                return ResourceManager.GetString("CreateTableWithUniqueColumnMsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE sys_metadata_kinds (
        ///uid UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
        ///title varchar(100) NOT NULL,
        ///prefix varchar(4) NOT NULL UNIQUE
        ///);.
        /// </summary>
        internal static string CreateTableWithUniqueColumnPgSql {
            get {
                return ResourceManager.GetString("CreateTableWithUniqueColumnPgSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 *
        ///FROM my_table;.
        /// </summary>
        internal static string SelectTopMsSql {
            get {
                return ResourceManager.GetString("SelectTopMsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT TOP 1 *
        ///FROM my_table
        ///ORDER BY name desc;.
        /// </summary>
        internal static string SelectTopOrderByMsSql {
            get {
                return ResourceManager.GetString("SelectTopOrderByMsSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM my_table
        ///ORDER BY name desc
        ///LIMIT 1;.
        /// </summary>
        internal static string SelectTopOrderByPgSql {
            get {
                return ResourceManager.GetString("SelectTopOrderByPgSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///FROM my_table
        ///LIMIT 1;.
        /// </summary>
        internal static string SelectTopPgSql {
            get {
                return ResourceManager.GetString("SelectTopPgSql", resourceCulture);
            }
        }
    }
}
